# Generated by Django 3.1 on 2020-08-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='upload_image',
        ),
        migrations.RemoveField(
            model_name='license',
            name='upload_image',
        ),
        migrations.RemoveField(
            model_name='other',
            name='upload_image',
        ),
        migrations.AddField(
            model_name='other',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other', to='app.autouser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='app.autouser'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('role', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='app.autouser')),
            ],
        ),
    ]
