# Generated by Django 3.1 on 2020-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200814_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
