# Generated by Django 3.1 on 2020-08-14 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200814_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to=settings.AUTH_USER_MODEL),
        ),
    ]
